[package]
name = "lighttable-text-layout-wasm"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen.workspace = true
read-fonts.workspace = true
skrifa.workspace = true
zeno.workspace = true
serde.workspace = true
serde_json.workspace = true
woff2-patched.workspace = true
parley.workspace = true
fontique.workspace = true
icu_segmenter.workspace = true
