// Generated by scripts/generate-third-party-inventory.mjs. Do not edit.
export const LIGHTTABLE_PRODUCT_DISCLOSURES = [
  {
    "category": "Application",
    "name": "React",
    "version": "19.2.8",
    "license": "MIT",
    "description": "Application interface runtime.",
    "platform": "all"
  },
  {
    "category": "Application",
    "name": "Dockview",
    "version": "7.0.4",
    "license": "MIT",
    "description": "Dockable panel and workspace layout.",
    "platform": "all"
  },
  {
    "category": "Documents and imaging",
    "name": "ag-psd",
    "version": "31.0.2",
    "license": "MIT",
    "description": "Photoshop document reading and writing.",
    "platform": "all"
  },
  {
    "category": "Documents and imaging",
    "name": "PDF.js",
    "version": "5.4.624",
    "license": "Apache-2.0",
    "description": "PDF document loading and rendering.",
    "platform": "all"
  },
  {
    "category": "Documents and imaging",
    "name": "pdf-lib",
    "version": "1.17.1",
    "license": "MIT",
    "description": "PDF document creation and editing.",
    "platform": "all"
  },
  {
    "category": "Text and fonts",
    "name": "HarfBuzz.js",
    "version": "1.5.0",
    "license": "MIT",
    "description": "OpenType text shaping.",
    "platform": "all"
  },
  {
    "category": "Text and fonts",
    "name": "Parley",
    "version": "0.11.0",
    "license": "Apache-2.0 OR MIT",
    "description": "Text layout engine.",
    "platform": "all"
  },
  {
    "category": "Text and fonts",
    "name": "Fontique",
    "version": "0.11.0",
    "license": "Apache-2.0 OR MIT",
    "description": "Font discovery and fallback.",
    "platform": "all"
  },
  {
    "category": "Text and fonts",
    "name": "Skrifa",
    "version": "0.43.2",
    "license": "MIT OR Apache-2.0",
    "description": "Font outline and metrics processing.",
    "platform": "all"
  },
  {
    "category": "Text and fonts",
    "name": "Zeno",
    "version": "0.3.3",
    "license": "Apache-2.0 OR MIT",
    "description": "Glyph outline rasterization.",
    "platform": "all"
  },
  {
    "category": "Bundled fonts",
    "name": "Inter",
    "version": "5.3.0",
    "license": "OFL-1.1",
    "description": "Bundled sans-serif typeface.",
    "platform": "all"
  },
  {
    "category": "Bundled fonts",
    "name": "Noto Sans",
    "version": "5.2.8",
    "license": "OFL-1.1",
    "description": "Bundled multilingual sans-serif typeface.",
    "platform": "all"
  },
  {
    "category": "Bundled fonts",
    "name": "Source Serif 4",
    "version": "5.2.8",
    "license": "OFL-1.1",
    "description": "Bundled serif typeface.",
    "platform": "all"
  },
  {
    "category": "Bundled fonts",
    "name": "JetBrains Mono",
    "version": "5.2.8",
    "license": "OFL-1.1",
    "description": "Bundled monospaced typeface.",
    "platform": "all"
  },
  {
    "category": "AI and automation",
    "name": "Transformers.js",
    "version": "3.8.1",
    "license": "Apache-2.0",
    "description": "Local machine-learning model runtime.",
    "platform": "all"
  },
  {
    "category": "Documents and imaging",
    "name": "wasm-vips codec bundle",
    "version": "0.0.18",
    "license": "LGPL-3.0 and bundled licenses",
    "description": "Native image codecs included in the WebAssembly image runtime.",
    "platform": "all"
  },
  {
    "category": "Application",
    "name": "Electron and Chromium runtime",
    "version": "39.8.10",
    "license": "MIT and bundled licenses",
    "description": "Desktop application and browser runtime.",
    "platform": "desktop"
  },
  {
    "category": "Text and fonts",
    "name": "HarfBuzz hb-gpu WGSL prototype",
    "version": "c31bd6797a0e",
    "license": "HarfBuzz old-style MIT license",
    "description": "Runtime component used by the GPU text pipeline.",
    "platform": "all"
  },
  {
    "category": "Documents and imaging",
    "name": "Compact ICC Profiles sRGB-v2-micro",
    "version": "0a8a33aea66a",
    "license": "CC0-1.0",
    "description": "Embedded product asset.",
    "platform": "all"
  },
  {
    "category": "AI and automation",
    "name": "onnx-community/depth-anything-v2-small-ONNX",
    "version": "Loaded on demand",
    "license": "Apache-2.0",
    "description": "Downloaded lazily when depth estimation is requested.",
    "platform": "all"
  }
] as const;
