/** Shared GPU layout for every shader that consumes an adjustment payload. */
export const ADJUSTMENTS_WGSL = /* wgsl */ `
struct Adjustments {
  temperature: f32,
  tint: f32,
  exposureEV: f32,
  contrast: f32,
  highlights: f32,
  shadows: f32,
  whites: f32,
  blacks: f32,
  clarity: f32,
  vibrance: f32,
  saturation: f32,
  texture: f32,
  dehaze: f32,
  vignette: f32,
  lift: f32,
  sourceWidth: f32,
  sourceHeight: f32,
  curveActive: f32,
  padding1: vec2f,
  mixerHue0: vec4f,
  mixerHue1: vec4f,
  mixerSaturation0: vec4f,
  mixerSaturation1: vec4f,
  mixerLuminance0: vec4f,
  mixerLuminance1: vec4f,
  gradingHue: vec4f,
  gradingSaturation: vec4f,
  gradingLuminance: vec4f,
  gradingControls: vec4f,
  gradientMapControls: vec4f,
  gradientMapColors: array<vec4f, 8>,
  gradientMapOpacity: array<vec4f, 8>,
  photoshop: array<vec4f, 60>,
  pointColor: array<vec4f, 24>,
  detail: array<vec4f, 3>,
  blackWhiteMix: array<vec4f, 3>,
  gradeLook: array<vec4f, 2>,
}
`;
