// Generated from ../catalog.json by scripts/generate-command-contract.mjs.
// Do not edit this file directly.

import commandCatalog from '../catalog.json' with { type: 'json' };

import parameterProperties from '../parameter-properties.json' with { type: 'json' };

import commandExamples from '../examples.json' with { type: 'json' };

import { createCommandBatchSchema } from './batch-schema.mjs';

import adjustmentCreationCommandSchemas from '../schemas/v1/adjustment-creation.json' with { type: 'json' };

import artifactCommandSchemas from '../schemas/v1/artifact.json' with { type: 'json' };

import autoAlignCommandSchemas from '../schemas/v1/auto-align.json' with { type: 'json' };

import finalizationCommandSchemas from '../schemas/v1/finalization.json' with { type: 'json' };

import gestureCommandSchemas from '../schemas/v1/gesture.json' with { type: 'json' };

import gradeBasicCommandSchemas from '../schemas/v1/grade-basic.json' with { type: 'json' };

import historyCommandSchemas from '../schemas/v1/history.json' with { type: 'json' };

import layerEffectsCommandSchemas from '../schemas/v1/layer-effects.json' with { type: 'json' };

import layerMaskCommandSchemas from '../schemas/v1/layer-mask.json' with { type: 'json' };

import layerStructureCommandSchemas from '../schemas/v1/layer-structure.json' with { type: 'json' };

import layerCommandSchemas from '../schemas/v1/layer.json' with { type: 'json' };

import mergeFlattenCommandSchemas from '../schemas/v1/merge-flatten.json' with { type: 'json' };

import rasterPaintCommandSchemas from '../schemas/v1/raster-paint.json' with { type: 'json' };

import selectionCommandSchemas from '../schemas/v1/selection.json' with { type: 'json' };

import taskCommandSchemas from '../schemas/v1/task.json' with { type: 'json' };

import textCommandSchemas from '../schemas/v1/text.json' with { type: 'json' };

import transformCommandSchemas from '../schemas/v1/transform.json' with { type: 'json' };

import vectorCommandSchemas from '../schemas/v1/vector.json' with { type: 'json' };

import viewCommandSchemas from '../schemas/v1/view.json' with { type: 'json' };

import warpCommandSchemas from '../schemas/v1/warp.json' with { type: 'json' };

export { validateJsonSchemaValue, formatSchemaValidationIssues } from './schema-validation.mjs';

const schemaReferences = (value, names = new Set()) => {
  if (Array.isArray(value)) value.forEach((entry) => schemaReferences(entry, names));
  else if (value && typeof value === 'object') {
    const match = typeof value.$ref === 'string' ? value.$ref.match(/^#\/\$defs\/([^/]+)$/u) : null;
    if (match) names.add(match[1]);
    Object.values(value).forEach((entry) => schemaReferences(entry, names));
  }
  return names;
};
const schemaWithDefinitions = (schema, definitions) => {
  const names = schemaReferences(schema);
  for (const name of names) {
    if (!definitions[name]) throw new Error(`Command schema references missing definition: ${name}.`);
    schemaReferences(definitions[name], names);
  }
  return names.size > 0 ? { ...schema, $defs: Object.fromEntries(
    [...names].map((name) => [name, definitions[name]])
  ) } : schema;
};
const schemaModuleCommands = (module) => module.$defs
  ? Object.fromEntries(Object.entries(module.commands).map(([id, schema]) => [id, {
      ...schema, input: schemaWithDefinitions(schema.input, module.$defs),
      result: schemaWithDefinitions(schema.result, module.$defs)
    }]))
  : module.commands;

export const LIGHTTABLE_COMMAND_PROTOCOL_VERSION = 1;

export const LIGHTTABLE_COMMAND_IDS = Object.freeze([
  'document.create',
  'document.duplicate',
  'document.resizeImage',
  'document.applyGeometry',
  'view.setZoom',
  'layer.createRaster',
  'layer.duplicate',
  'layer.copyToNewLayer',
  'layer.delete',
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setTransform',
  'transform.applyFixed',
  'adjustment.create',
  'raster.invert',
  'text.convertToShape',
  'text.rasterize',
  'layer.merge',
  'layer.flattenGroup',
  'document.flattenImage',
  'layer.setMask',
  'layer.removeBackground',
  'layer.autoAlign',
  'layer.setLock',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.style.update',
  'layer.effect.setEnabled',
  'file.openArtifact',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'warp.applyStroke',
  'raster.fill',
  'raster.applyGradient',
  'faceWarp.applyOperation',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'command.batch',
  'tool.commitGesture',
  'selection.applyShape',
  'selection.applyMagicWand',
  'selection.selectSubject',
  'selection.modify',
  'grade.setBasic',
  'task.cancel',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
]);

export const LIGHTTABLE_COMMAND_DEFINITIONS = Object.freeze(commandCatalog.commands);

export const LIGHTTABLE_COMMAND_PARAMETER_PROPERTIES = Object.freeze(parameterProperties);

export const LIGHTTABLE_COMMAND_EXAMPLES = Object.freeze(commandExamples);

export const LIGHTTABLE_COMMAND_SCHEMA_VERSION = 1;

const baseCommandSchemas = Object.freeze({
  ...schemaModuleCommands(adjustmentCreationCommandSchemas),
  ...schemaModuleCommands(artifactCommandSchemas),
  ...schemaModuleCommands(autoAlignCommandSchemas),
  ...schemaModuleCommands(finalizationCommandSchemas),
  ...schemaModuleCommands(gestureCommandSchemas),
  ...schemaModuleCommands(gradeBasicCommandSchemas),
  ...schemaModuleCommands(historyCommandSchemas),
  ...schemaModuleCommands(layerEffectsCommandSchemas),
  ...schemaModuleCommands(layerMaskCommandSchemas),
  ...schemaModuleCommands(layerStructureCommandSchemas),
  ...schemaModuleCommands(layerCommandSchemas),
  ...schemaModuleCommands(mergeFlattenCommandSchemas),
  ...schemaModuleCommands(rasterPaintCommandSchemas),
  ...schemaModuleCommands(selectionCommandSchemas),
  ...schemaModuleCommands(taskCommandSchemas),
  ...schemaModuleCommands(textCommandSchemas),
  ...schemaModuleCommands(transformCommandSchemas),
  ...schemaModuleCommands(vectorCommandSchemas),
  ...schemaModuleCommands(viewCommandSchemas),
  ...schemaModuleCommands(warpCommandSchemas)
});

export const LIGHTTABLE_COMMAND_SCHEMAS = Object.freeze({
  ...baseCommandSchemas,
  'command.batch': createCommandBatchSchema(baseCommandSchemas, [
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setLock',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.effect.setEnabled',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move'
])
});

export const LIGHTTABLE_AGENT_ACCESS_COMMAND_IDS = Object.freeze([
  'document.create',
  'view.setZoom',
  'layer.createRaster',
  'layer.duplicate',
  'layer.copyToNewLayer',
  'layer.delete',
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setTransform',
  'transform.applyFixed',
  'adjustment.create',
  'raster.invert',
  'text.convertToShape',
  'text.rasterize',
  'layer.merge',
  'layer.flattenGroup',
  'document.flattenImage',
  'layer.setMask',
  'layer.removeBackground',
  'layer.autoAlign',
  'layer.setLock',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.style.update',
  'layer.effect.setEnabled',
  'file.openArtifact',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'warp.applyStroke',
  'raster.fill',
  'raster.applyGradient',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'command.batch',
  'tool.commitGesture',
  'selection.applyShape',
  'selection.applyMagicWand',
  'selection.selectSubject',
  'selection.modify',
  'grade.setBasic',
  'task.cancel',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
]);

export const LIGHTTABLE_EXTERNAL_MCP_EXECUTE_COMMAND_IDS = Object.freeze([
  'view.setZoom',
  'layer.createRaster',
  'layer.duplicate',
  'layer.copyToNewLayer',
  'layer.delete',
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setTransform',
  'transform.applyFixed',
  'adjustment.create',
  'raster.invert',
  'text.convertToShape',
  'text.rasterize',
  'layer.merge',
  'layer.flattenGroup',
  'document.flattenImage',
  'layer.setMask',
  'layer.removeBackground',
  'layer.autoAlign',
  'layer.setLock',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.style.update',
  'layer.effect.setEnabled',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'warp.applyStroke',
  'raster.fill',
  'raster.applyGradient',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'command.batch',
  'tool.commitGesture',
  'selection.applyShape',
  'selection.applyMagicWand',
  'selection.selectSubject',
  'selection.modify',
  'grade.setBasic',
  'task.cancel',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
]);

export const LIGHTTABLE_EXTERNAL_MCP_DEDICATED_COMMAND_IDS = Object.freeze([
  'document.create',
  'file.openArtifact'
]);

export const LIGHTTABLE_EXTERNAL_MCP_BATCH_OPERATION_IDS = Object.freeze([
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setLock',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.effect.setEnabled',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move'
]);

const commandIds = new Set(LIGHTTABLE_COMMAND_IDS);
const agentAccessCommandIds = new Set(LIGHTTABLE_AGENT_ACCESS_COMMAND_IDS);

export const isLightTableCommandId = (value) => typeof value === 'string' && commandIds.has(value);
export const isLightTableAgentAccessCommandId = (value) => typeof value === 'string' && agentAccessCommandIds.has(value);
