// Generated from ../catalog.json by scripts/generate-command-contract.mjs.
// Do not edit this file directly.

export declare const LIGHTTABLE_COMMAND_PROTOCOL_VERSION: 1;

export declare const LIGHTTABLE_COMMAND_IDS: readonly [
  'document.create',
  'document.duplicate',
  'document.resizeImage',
  'document.applyGeometry',
  'view.setZoom',
  'layer.createRaster',
  'layer.duplicate',
  'layer.delete',
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setTransform',
  'transform.applyFixed',
  'adjustment.create',
  'layer.setMask',
  'layer.setLock',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.effect.setEnabled',
  'file.openArtifact',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'warp.applyStroke',
  'raster.fill',
  'raster.applyGradient',
  'faceWarp.applyOperation',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'command.batch',
  'tool.commitGesture',
  'selection.applyShape',
  'selection.applyMagicWand',
  'selection.modify',
  'grade.setBasic',
  'task.cancel',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
];

export type LightTableCommandId = typeof LIGHTTABLE_COMMAND_IDS[number];

export type LightTableCommandCategory = 'document' | 'image' | 'view' | 'layer' | 'effects' | 'file' | 'text' | 'vector' | 'selection' | 'automation' | 'history';
export interface LightTableCommandDefinition { readonly id: LightTableCommandId; readonly category: LightTableCommandCategory; readonly label: string; readonly description: string; readonly scope: 'workspace' | 'document'; readonly effect: 'presentation' | 'edit' | 'external-io' | 'control'; readonly invocation: 'direct' | 'parameters'; readonly agentAccess: boolean; readonly agentAccessReason?: string; readonly externalMcp: 'execute' | 'dedicated' | null; readonly externalMcpReason?: string; readonly atomicBatch?: boolean; }
export declare const LIGHTTABLE_COMMAND_DEFINITIONS: readonly LightTableCommandDefinition[];

export type LightTableCommandParameterProperties = Readonly<Record<string, string>>;
export declare const LIGHTTABLE_COMMAND_PARAMETER_PROPERTIES: Readonly<Record<LightTableCommandId, LightTableCommandParameterProperties>>;

export declare const LIGHTTABLE_COMMAND_EXAMPLES: Readonly<Partial<Record<LightTableCommandId, readonly Readonly<Record<string, unknown>>[]>>>;

export declare const LIGHTTABLE_AGENT_ACCESS_COMMAND_IDS: readonly [
  'document.create',
  'view.setZoom',
  'layer.createRaster',
  'layer.duplicate',
  'layer.delete',
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setTransform',
  'transform.applyFixed',
  'adjustment.create',
  'layer.setMask',
  'layer.setLock',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.effect.setEnabled',
  'file.openArtifact',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'warp.applyStroke',
  'raster.fill',
  'raster.applyGradient',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'command.batch',
  'tool.commitGesture',
  'selection.applyShape',
  'selection.applyMagicWand',
  'selection.modify',
  'grade.setBasic',
  'task.cancel',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
];

export type LightTableAgentAccessCommandId = typeof LIGHTTABLE_AGENT_ACCESS_COMMAND_IDS[number];

export declare const LIGHTTABLE_EXTERNAL_MCP_EXECUTE_COMMAND_IDS: readonly [
  'view.setZoom',
  'layer.createRaster',
  'layer.duplicate',
  'layer.delete',
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setTransform',
  'transform.applyFixed',
  'adjustment.create',
  'layer.setMask',
  'layer.setLock',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.effect.setEnabled',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'warp.applyStroke',
  'raster.fill',
  'raster.applyGradient',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'command.batch',
  'tool.commitGesture',
  'selection.applyShape',
  'selection.applyMagicWand',
  'selection.modify',
  'grade.setBasic',
  'task.cancel',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
];

export declare const LIGHTTABLE_EXTERNAL_MCP_DEDICATED_COMMAND_IDS: readonly [
  'document.create',
  'file.openArtifact'
];

export declare const LIGHTTABLE_EXTERNAL_MCP_BATCH_OPERATION_IDS: readonly [
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setLock',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.effect.setEnabled',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move'
];

export declare const isLightTableCommandId: (value: unknown) => value is LightTableCommandId;
export declare const isLightTableAgentAccessCommandId: (value: unknown) => value is LightTableAgentAccessCommandId;
