// Generated from ../catalog.json by scripts/generate-command-contract.mjs.
// Do not edit this file directly.

export declare const LIGHTTABLE_COMMAND_PROTOCOL_VERSION: 1;

export declare const LIGHTTABLE_COMMAND_IDS: readonly [
  'document.create',
  'document.duplicate',
  'document.resizeImage',
  'document.applyGeometry',
  'view.setZoom',
  'layer.createRaster',
  'layer.duplicate',
  'layer.copyToNewLayer',
  'layer.delete',
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setTransform',
  'transform.applyFixed',
  'adjustment.create',
  'raster.invert',
  'text.convertToShape',
  'text.rasterize',
  'layer.merge',
  'layer.flattenGroup',
  'document.flattenImage',
  'layer.setMask',
  'layer.removeBackground',
  'layer.autoAlign',
  'layer.setLock',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.style.update',
  'layer.effect.setEnabled',
  'file.openArtifact',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'warp.applyStroke',
  'raster.fill',
  'raster.applyGradient',
  'faceWarp.applyOperation',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'command.batch',
  'tool.commitGesture',
  'selection.applyShape',
  'selection.applyMagicWand',
  'selection.selectSubject',
  'selection.modify',
  'grade.setBasic',
  'task.cancel',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
];

export type LightTableCommandId = typeof LIGHTTABLE_COMMAND_IDS[number];

export type LightTableCommandCategory = 'document' | 'image' | 'view' | 'layer' | 'effects' | 'file' | 'text' | 'vector' | 'selection' | 'automation' | 'history';
export interface LightTableCommandDefinition { readonly id: LightTableCommandId; readonly category: LightTableCommandCategory; readonly label: string; readonly description: string; readonly scope: 'workspace' | 'document'; readonly effect: 'presentation' | 'edit' | 'external-io' | 'control'; readonly invocation: 'direct' | 'parameters'; readonly agentAccess: boolean; readonly agentAccessReason?: string; readonly externalMcp: 'execute' | 'dedicated' | null; readonly externalMcpReason?: string; readonly atomicBatch?: boolean; }
export declare const LIGHTTABLE_COMMAND_DEFINITIONS: readonly LightTableCommandDefinition[];

export type LightTableCommandParameterProperties = Readonly<Record<string, string>>;
export declare const LIGHTTABLE_COMMAND_PARAMETER_PROPERTIES: Readonly<Record<LightTableCommandId, LightTableCommandParameterProperties>>;

export declare const LIGHTTABLE_COMMAND_EXAMPLES: Readonly<Partial<Record<LightTableCommandId, readonly Readonly<Record<string, unknown>>[]>>>;

export interface LightTableJsonSchema { readonly type?: 'object' | 'array' | 'string' | 'number' | 'integer' | 'boolean'; readonly title?: string; readonly description?: string; readonly properties?: Readonly<Record<string, LightTableJsonSchema>>; readonly required?: readonly string[]; readonly additionalProperties?: boolean; readonly minProperties?: number; readonly maxProperties?: number; readonly items?: LightTableJsonSchema; readonly enum?: readonly unknown[]; readonly const?: unknown; readonly default?: unknown; readonly minLength?: number; readonly maxLength?: number; readonly pattern?: string; readonly minItems?: number; readonly maxItems?: number; readonly uniqueItems?: boolean; readonly minimum?: number; readonly maximum?: number; readonly allOf?: readonly LightTableJsonSchema[]; readonly anyOf?: readonly LightTableJsonSchema[]; readonly oneOf?: readonly LightTableJsonSchema[]; readonly not?: LightTableJsonSchema; readonly if?: LightTableJsonSchema; readonly then?: LightTableJsonSchema; readonly else?: LightTableJsonSchema; readonly $ref?: string; readonly $defs?: Readonly<Record<string, LightTableJsonSchema>>; readonly 'x-lighttable-control'?: 'layer-id' | 'layer-ids'; readonly 'x-lighttable-step'?: number; readonly 'x-lighttable-variant-editor'?: boolean; }
export interface LightTableCommandSchema { readonly input: LightTableJsonSchema; readonly result: LightTableJsonSchema; }
export interface LightTableSchemaValidationIssue { readonly path: readonly (string | number)[]; readonly code: string; readonly message: string; }
export type LightTableSchemaValidationResult = { readonly valid: true; readonly issues: readonly [] } | { readonly valid: false; readonly issues: readonly LightTableSchemaValidationIssue[] };
export declare const LIGHTTABLE_COMMAND_SCHEMA_VERSION: 1;
export declare const LIGHTTABLE_COMMAND_SCHEMAS: Readonly<Partial<Record<LightTableCommandId, LightTableCommandSchema>>>;
export declare const validateJsonSchemaValue: (schema: LightTableJsonSchema, value: unknown) => LightTableSchemaValidationResult;
export declare const formatSchemaValidationIssues: (issues: readonly LightTableSchemaValidationIssue[]) => string;

export declare const LIGHTTABLE_AGENT_ACCESS_COMMAND_IDS: readonly [
  'document.create',
  'document.resizeImage',
  'document.applyGeometry',
  'view.setZoom',
  'layer.createRaster',
  'layer.duplicate',
  'layer.copyToNewLayer',
  'layer.delete',
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setTransform',
  'transform.applyFixed',
  'adjustment.create',
  'raster.invert',
  'text.convertToShape',
  'text.rasterize',
  'layer.merge',
  'layer.flattenGroup',
  'document.flattenImage',
  'layer.setMask',
  'layer.removeBackground',
  'layer.autoAlign',
  'layer.setLock',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.style.update',
  'layer.effect.setEnabled',
  'file.openArtifact',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'warp.applyStroke',
  'raster.fill',
  'raster.applyGradient',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'command.batch',
  'tool.commitGesture',
  'selection.applyShape',
  'selection.applyMagicWand',
  'selection.selectSubject',
  'selection.modify',
  'grade.setBasic',
  'task.cancel',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
];

export type LightTableAgentAccessCommandId = typeof LIGHTTABLE_AGENT_ACCESS_COMMAND_IDS[number];

export declare const LIGHTTABLE_EXTERNAL_MCP_EXECUTE_COMMAND_IDS: readonly [
  'document.resizeImage',
  'document.applyGeometry',
  'view.setZoom',
  'layer.createRaster',
  'layer.duplicate',
  'layer.copyToNewLayer',
  'layer.delete',
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setTransform',
  'transform.applyFixed',
  'adjustment.create',
  'raster.invert',
  'text.convertToShape',
  'text.rasterize',
  'layer.merge',
  'layer.flattenGroup',
  'document.flattenImage',
  'layer.setMask',
  'layer.removeBackground',
  'layer.autoAlign',
  'layer.setLock',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.style.update',
  'layer.effect.setEnabled',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'warp.applyStroke',
  'raster.fill',
  'raster.applyGradient',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'command.batch',
  'tool.commitGesture',
  'selection.applyShape',
  'selection.applyMagicWand',
  'selection.selectSubject',
  'selection.modify',
  'grade.setBasic',
  'task.cancel',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
];

export declare const LIGHTTABLE_EXTERNAL_MCP_DEDICATED_COMMAND_IDS: readonly [
  'document.create',
  'file.openArtifact'
];

export declare const LIGHTTABLE_EXTERNAL_MCP_BATCH_OPERATION_IDS: readonly [
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setLock',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.effect.setEnabled',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move'
];

export declare const isLightTableCommandId: (value: unknown) => value is LightTableCommandId;
export declare const isLightTableAgentAccessCommandId: (value: unknown) => value is LightTableAgentAccessCommandId;
