// Generated from ../catalog.json by scripts/generate-command-contract.mjs.
// Do not edit this file directly.

import commandCatalog from '../catalog.json' with { type: 'json' };

import parameterProperties from '../parameter-properties.json' with { type: 'json' };

import commandExamples from '../examples.json' with { type: 'json' };

export const LIGHTTABLE_COMMAND_PROTOCOL_VERSION = 1;

export const LIGHTTABLE_COMMAND_IDS = Object.freeze([
  'document.create',
  'document.duplicate',
  'document.resizeImage',
  'document.applyGeometry',
  'view.setZoom',
  'layer.createRaster',
  'layer.duplicate',
  'layer.delete',
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setTransform',
  'transform.applyFixed',
  'adjustment.create',
  'raster.invert',
  'layer.setMask',
  'layer.setLock',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.effect.setEnabled',
  'file.openArtifact',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'warp.applyStroke',
  'raster.fill',
  'raster.applyGradient',
  'faceWarp.applyOperation',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'command.batch',
  'tool.commitGesture',
  'selection.applyShape',
  'selection.applyMagicWand',
  'selection.modify',
  'grade.setBasic',
  'task.cancel',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
]);

export const LIGHTTABLE_COMMAND_DEFINITIONS = Object.freeze(commandCatalog.commands);

export const LIGHTTABLE_COMMAND_PARAMETER_PROPERTIES = Object.freeze(parameterProperties);

export const LIGHTTABLE_COMMAND_EXAMPLES = Object.freeze(commandExamples);

export const LIGHTTABLE_AGENT_ACCESS_COMMAND_IDS = Object.freeze([
  'document.create',
  'view.setZoom',
  'layer.createRaster',
  'layer.duplicate',
  'layer.delete',
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setTransform',
  'transform.applyFixed',
  'adjustment.create',
  'raster.invert',
  'layer.setMask',
  'layer.setLock',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.effect.setEnabled',
  'file.openArtifact',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'warp.applyStroke',
  'raster.fill',
  'raster.applyGradient',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'command.batch',
  'tool.commitGesture',
  'selection.applyShape',
  'selection.applyMagicWand',
  'selection.modify',
  'grade.setBasic',
  'task.cancel',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
]);

export const LIGHTTABLE_EXTERNAL_MCP_EXECUTE_COMMAND_IDS = Object.freeze([
  'view.setZoom',
  'layer.createRaster',
  'layer.duplicate',
  'layer.delete',
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setTransform',
  'transform.applyFixed',
  'adjustment.create',
  'raster.invert',
  'layer.setMask',
  'layer.setLock',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.effect.setEnabled',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'warp.applyStroke',
  'raster.fill',
  'raster.applyGradient',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'command.batch',
  'tool.commitGesture',
  'selection.applyShape',
  'selection.applyMagicWand',
  'selection.modify',
  'grade.setBasic',
  'task.cancel',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
]);

export const LIGHTTABLE_EXTERNAL_MCP_DEDICATED_COMMAND_IDS = Object.freeze([
  'document.create',
  'file.openArtifact'
]);

export const LIGHTTABLE_EXTERNAL_MCP_BATCH_OPERATION_IDS = Object.freeze([
  'layer.move',
  'layer.setBlendMode',
  'layer.setClipping',
  'layer.setLock',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.effect.setEnabled',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move'
]);

const commandIds = new Set(LIGHTTABLE_COMMAND_IDS);
const agentAccessCommandIds = new Set(LIGHTTABLE_AGENT_ACCESS_COMMAND_IDS);

export const isLightTableCommandId = (value) => typeof value === 'string' && commandIds.has(value);
export const isLightTableAgentAccessCommandId = (value) => typeof value === 'string' && agentAccessCommandIds.has(value);
