// Generated from ../catalog.json by scripts/generate-command-contract.mjs.
// Do not edit this file directly.

export declare const LIGHTTABLE_COMMAND_PROTOCOL_VERSION: 1;

export declare const LIGHTTABLE_COMMAND_IDS: readonly [
  'document.create',
  'document.duplicate',
  'document.resizeImage',
  'document.applyGeometry',
  'view.setZoom',
  'layer.createRaster',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.effect.setEnabled',
  'file.openArtifact',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'faceWarp.applyOperation',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'command.batch',
  'task.cancel',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
];

export type LightTableCommandId = typeof LIGHTTABLE_COMMAND_IDS[number];

export declare const LIGHTTABLE_AGENT_ACCESS_COMMAND_IDS: readonly [
  'document.create',
  'view.setZoom',
  'layer.createRaster',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.effect.setEnabled',
  'file.openArtifact',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'command.batch',
  'task.cancel',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
];

export type LightTableAgentAccessCommandId = typeof LIGHTTABLE_AGENT_ACCESS_COMMAND_IDS[number];

export declare const LIGHTTABLE_EXTERNAL_MCP_EXECUTE_COMMAND_IDS: readonly [
  'view.setZoom',
  'layer.createRaster',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.effect.setEnabled',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'command.batch',
  'task.cancel',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
];

export declare const LIGHTTABLE_EXTERNAL_MCP_DEDICATED_COMMAND_IDS: readonly [
  'document.create',
  'file.openArtifact'
];

export declare const LIGHTTABLE_EXTERNAL_MCP_BATCH_OPERATION_IDS: readonly [
  'view.setZoom',
  'layer.createRaster',
  'layer.placeArtifact',
  'layer.rename',
  'layer.setVisibility',
  'layer.setFillOpacity',
  'layer.style.setEnabled',
  'layer.effect.setEnabled',
  'text.create',
  'text.replaceRange',
  'text.format',
  'text.setLayout',
  'vector.create',
  'vector.update',
  'vector.remove',
  'layer.effect.add',
  'layer.effect.update',
  'layer.effect.remove',
  'layer.effect.move',
  'file.exportNative',
  'file.exportPng',
  'file.exportPsd',
  'history.undo',
  'history.redo'
];

export declare const isLightTableCommandId: (value: unknown) => value is LightTableCommandId;
export declare const isLightTableAgentAccessCommandId: (value: unknown) => value is LightTableAgentAccessCommandId;
